

export const SET_EDIT_FF_USER="SET_EDIT_FF_USER"
export const SET_FOLLOWING="SET_FOLLOWING"
export const SET_FOLLOWERS="SET_FOLLOWERS"
export const SET_FF_COUNT="SET_FF_COUNT"
export const SET_FF_VISIBILITY="SET_FF_VISIBILITY"
